version: '2.1'
orbs:
  matlab: mathworks/matlab@0
jobs:
  build:
    machine:
      image: 'ubuntu-2204:current'
    resource_class: large
    steps:
      - run:
          name: Checkout code via HTTPS
          command: |
            git clone https://github.com/moiseevigor/elliptic.git .
            git checkout $CIRCLE_SHA1
      - matlab/install
      - matlab/run-tests:
          test-results-junit: test-results/results.xml
          logging-level: 'Detailed'
          select-by-folder: matlab/tests
          source-folder: matlab/src
      - store_test_results:
          path: test-results
  build-octave:
    docker:
      - image: gnuoctave/octave:9.2.0
    steps:
      - run:
          name: Checkout code via HTTPS
          command: |
            apt-get update && apt-get install -y git
            git clone https://github.com/moiseevigor/elliptic.git .
            git checkout $CIRCLE_SHA1
      - run:
          name: Run Octave tests
          command: |
            octave --eval "addpath(fullfile(pwd, 'matlab', 'src')); cd matlab/tests; test testElliptic12; test testElliptic3; test testEllipj; test testThetaPrime; test testAgm; test testJacobiThetaEta;"
workflows:
  build:
    jobs:
      - build
      - build-octave
